-keep class kotlinx.serialization.** { *; }
-keep @kotlinx.serialization.Serializable class * { *; }
-keep class dagger.hilt.** { *; }
-keep class com.google.** { *; }
-dontwarn kotlinx.serialization.**
